
[tool.poetry]
name = "procrastinate"
version = "0.0.0"
description = "Postgres-based distributed task processing library"
authors = ["Joachim Jablon", "Eric Lemoine"]
license = "MIT License"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "License :: OSI Approved :: MIT License",
]
readme = "README.rst"
keywords = ["postgres", "task-queue"]
homepage = "https://procrastinate.readthedocs.io/"
repository = "https://github.com/procrastinate-org/procrastinate/"
documentation = "https://procrastinate.readthedocs.io/"

[tool.poetry.scripts]
procrastinate = 'procrastinate.cli:main'

[tool.poetry.dependencies]
python = "^3.7"
aiopg = "*"
asgiref = "*"
attrs = "*"
click = "*"
croniter = "*"
django = {version = ">=2.2", optional = true}
importlib-metadata = {version = "*", python = "<3.8"}
importlib-resources = {version = ">=1.4", python = "<3.9"}
psycopg2-binary = "*"
python-dateutil = "*"
sqlalchemy = {version = "^2.0", optional = true}
typing-extensions = {version = "*", python = "<3.8"}

[tool.poetry.extras]
django = ["django"]
sqlalchemy = ["sqlalchemy"]

[tool.poetry.group.dev.dependencies]
black = "*"
dunamai = "*"
flake8 = "*"
migra = "*"
mypy = "*"
pytest-asyncio = "*"
pytest-click = "*"
pytest-cov = "*"
pytest-django = "*"
pytest-mock = "*"
Sphinx = "*"
sphinx-autodoc-typehints = "*"
sphinx-github-changelog = "*"
sphinxcontrib-programoutput = "*"
sqlalchemy = {extras = ["mypy"], version = "*"}
types-croniter = "*"
types-psycopg2 = "*"
types-python-dateutil = "*"
SQLAlchemy = {extras = ["mypy"], version = "^2.0.0"}
tomlkit = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
